[env:esp32-c3-supermini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200

; USB CDC on Boot is required for the ESP32-C3 Supermini to output Serial data over its USB port
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
	adafruit/Adafruit SSD1306 @ ^2.5.7
	adafruit/Adafruit GFX Library @ ^1.11.5
	bblanchon/ArduinoJson @ ^6.21.3
